---
extends: default

ignore-from-file: [.gitignore]

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  comments:
    # prettier compatibility
    min-spaces-from-content: 1
  comments-indentation: false
  line-length:
    max: 120
    level: warning
  quoted-strings:
    quote-type: double
    required: only-when-needed
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
